version: '3'
services:
  force-grapher:
    container_name: force-grapher
    build:
      context: .
    ports: 
      - 3000:3000
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
  mongodb:
    container_name: graphdb
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - forcegrapher:/data/db
volumes:
  forcegrapher: {}
